### PR TITLE
Syntax in a nutshell

### PR DESCRIPTION
**Pull request by gocko**

### CODE REVIEW

**Comment by gocko** [comment]
Do we need to introduce a summary of reserved characters like #, $, ., ' ...', <...>,(...), [...], ... with all core meanings?

**Comment by gocko** [comment]
should we add some ref for MapReduce?

**Comment by Ducasse** [comment]
Why? I would not because else we should put a ref to lisp and others.

**Comment by gocko** [comment]
Yes, therefore. If this book is for beginners we can expect a reader to be familiar with basic OO concepts, but MapReduce does not belong there. If we agree we should, we can also reference basic concepts unrelated to any language such as higher-order functions.

**Comment by gocko** [comment]
Done (once)

**Pull request merged**
